 
 [[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    Content-Type = "application/javascript; charset=utf-8"
    Content-Type = "text/html; charset=utf-8"
    Content-Type = "text/css;"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self';"
