 
 [[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = '''
    default-src 'self';
    script-src 'self';
    style-src 'self';
    object-src 'none';
    img-src 'self';
    media-src 'none';
    frame-src 'none';
    font-src 'self';
    connect-src 'none';
    
    '''
      X-Content-Security-Policy = '''
    default-src 'self';
    script-src 'self';
    style-src 'self';
    object-src 'none';
    img-src 'self';
    media-src 'none';
    frame-src 'none';
    font-src 'self';
    connect-src 'none';
    
    '''
      X-WebKit-CSP = '''
    default-src 'self';
    script-src 'self';
    style-src 'self';
    object-src 'none';
    img-src 'self';
    media-src 'none';
    frame-src 'none';
    font-src 'self';
    connect-src 'none';
    
    '''
